id = "gram"
name = "Gram Language Support"
version = "0.3.8"
schema_version = 1
authors = ["Gram Data Contributors"]
description = "Support for Gram notation - composable data patterns"

capabilities = [
  { kind = "process:exec", command = "*", args = ["stdio"] },
  { kind = "download_file", host = "github.com", path = ["gram-data", "tree-sitter-gram", "**"] },
]

# path = "grammars/tree-sitter-gram"
[grammars.gram]
repository = "file:///Users/akollegger/Developer/gram-data/tree-sitter-gram"
rev = "1f99e729c8614654d0072c54fce55ddd6ff4d1f8"
